apiVersion: v1
kind: Pod
metadata:
  name: bdiscount-items-back
  labels:
    app: bdiscount-items-back
spec:
  containers:
    - name: bdiscount-items-back
      image: tekxover/bdiscount-items-back:1.5
      ports:
        - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: bdiscount-items-back
spec:
  type: NodePort
  selector:
    app: bdiscount-items-back
  ports:
    - port: 3000
      targetPort: 3000